### ISSUE TITLE
Move google drive files here

### ISSUE THREAD

**Issue by oxinabox** [HealthHackAu2016/per-adhd#1]
Can all the files be downloaded out of google drive,
and upload them here.

**Comment by vanbujm** [comment]
That's a lot of binary files... I'd rather just share the link to the drive in the read me.

**Comment by oxinabox** [comment]
I think that I don't trust that drive to have correct permissions set up.

This is an achieve repo at this point.
Better to put it all in the archive.

**Comment by vanbujm** [comment]
Go for it then. :P
